[package]
name = "btsdu"
version = "0.1.0"
authors = ["Roman Kapl <code@rkapl.cz>"]

[dependencies]
btrfs-send-parse = {path = "../btrfs-send-parse"}
clap = "2.32.0"
serde_json = "1.0.22"
serde = "1.0.69"
serde_derive = "1.0.69"